plugins {
    id 'com.android.application'
}

android {
    namespace 'com.musichub.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.musichub.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
}
